### ISSUE TITLE
Simply won't show

### ISSUE THREAD

**Issue by catzybluphish** [Jvanrhijn/polybar-spotify#10]
Been using the lovely script for a while now with no problems until I switched to Void today and found out that it doesn't work. I have python, python3 and python-dbus installed. When I didn't have a python_status.py, polybar would whine about how the file doesn't exist but when I do make one, although the error disappears from the bar, doesn't show anything when I have a song playing when using Spotify. The script has always worked when on Arch so it may be something about Void...

Edit: I've changed to and tried the default settings suggested on this git page as well to no avail.

**Comment by alexfornuto** [comment]
@catzybluphish  care to share how you solved? I'm in the same boat.

**Comment by ghost** [comment]
Just for future reference, I got this running by changing my .xinitrc from:
exec bspwm

to:
exec dbus-launch --autolaunch=$(cat /var/lib/dbus/machine-id) bspwm

This came straight from the playerctl documentation which I was gonna try since this was not working (it works with the change above).
