### ISSUE TITLE
Traceback error ( import dbus )

### ISSUE THREAD

**Issue by Gho0stDev** [Jvanrhijn/polybar-spotify#32]
Hi!
so, I downloaded and installed the script the way it was described in the README.
but when I finish configuring it gives an error

"`Traceback (most recent call last)`"

then I tried to run it through the terminal... the error appeared completely.

```
[Gho0st@archlinux scripts]$ python spotify_status.py
Traceback (most recent call last):
   File "/home/Gho0st/.config/polybar/scripts/spotify_status.py", line 4, in <module>
     import dbus
ModuleNotFoundError: No module named 'dbus'
```

I installed dbus with :

`sudo pacman -S dbus`

but it keeps giving the error... can you help me?

**Comment by Jvanrhijn** [comment]
The `dbus` package on arch is not the same as the Python module. Try installing `dbus-python`, it should work after that (and let me know if it does so I can close the issue).

**Comment by Gho0stDev** [comment]
oh, thanks !!
