### ISSUE TITLE
format-underline color not displaying

### ISSUE THREAD

**Issue by Nano-Sec** [Jvanrhijn/polybar-spotify#6]
The hex on format underline doesn't seem to show up on the bar.

**Comment by Jvanrhijn** [comment]
Could you attach your polybar config file?

**Comment by Nano-Sec** [comment]
`[bar/white]

;------------;
; DIMENSIONS ;
;------------;

width = 100%
height = 40
offset-y = 0
offset-x = 0

border-top-size = 0
border-bottom-size = 0
border-right-size = 0
border-left-size = 0

;----------;
; LOCATION ;
;----------;

bottom = true
wm-restack = none
override-redirect = false

;-------;
; FONTS ;
;-------;

font-0 = Sans:size=14;3
font-1 = "Font Awesome 5 Free:style=Solid:pixelsize=18;3"
font-2 = "Font Awesome 5 Free:style=Regular:pixelsize=18;3"
font-3 = "Font Awesome 5 Brands:pixelsize=18;3"

;--------;
; COLORS ;
;--------;

background = #1d1f21
foreground = #ffffff
border-color = 0

;---------------;
; MISCELLANEOUS ;
;---------------;

fixed-center = true
padding-left = 2.5
padding-right = 2.5
module-margin = 2.5

modules-left = volume spotify
modules-center = i3
modules-right = cpu date time

tray-position = none
tray-detached = true

;---------;
; MODULES ;
;---------;

[module/i3]
type = internal/i3

pin-workspaces = true
strip-wsnumbers = true
enable-scroll = false

label-unfocused-foreground = #afafaf
label-focused-foreground = #bc646f
label-urgent-foreground = #ff0000

[module/time]
type = internal/date

interval = 1.0

date =  %H:%M

[module/date]
type = internal/date
date =  %e %B - %A
label = %date%

[module/volume]
type = internal/alsa

format-volume = <ramp-volume> <label-volume>
format-muted =  0%

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

mapped = true

[module/cpu]
type = internal/cpu
label =  %percentage%%


[module/memory]
type = internal/memory
label =  %gb_used%

[module/network]
type = internal/network
interface = wlp2s0
label-connected =  %downspeed% |  %upspeed%

[module/spotify]
type = custom/script
interval = 1
format-prefix = "  "
format = <label>
exec = python ~/Documents/polybar-spotify/spotify_status.py
format-underline = #1db954

[bar/float]

inherit = bar/white

background = #ffffff

tray-position = center`

**Comment by Jvanrhijn** [comment]
Adding `line-size = x` (I have x = 3) in your [bar/white] section draws the line.

**Comment by Nano-Sec** [comment]
Thanks. Works fine now.
