### ISSUE TITLE
Songs or artists with letters æøå is giving an error message

### ISSUE THREAD

**Issue by misterdohl** [Jvanrhijn/polybar-spotify#8]
'ascii' codec can't encode character u'\u25b6' in position 0: ordinal not in range(128)

Probably something with the charset and easy to fix :)

**Comment by Jvanrhijn** [comment]
Can you give me an example of a song with one of those characters?

**Comment by misterdohl** [comment]
https://open.spotify.com/track/61mTvagExZvija6RD4IfiC?si=AM0QGFRxR1ejt6pZbdKiOA

**Comment by Jvanrhijn** [comment]
26f7602206f5c10f9a9d05a4e06d4be666c72ded should fix this; can you confirm?

**Comment by misterdohl** [comment]
tried adding a u in front like shown, but got the same results.
maybe try decoding from iso-8859-1?

**Comment by Jvanrhijn** [comment]
What version of python are you running? (`python --version`)
Testing this fix with both `python2` (version 2.7.15) and `python3` (version 3.6.6) shows the correct output for me.

**Comment by misterdohl** [comment]
$ cat spotify_status.py | grep "output = u"
output = u'{play_pause} {artist}: {song}'
$ python --version
Python 2.7.15rc1

I can see that it works in the terminal when running the script, but polybar is showing same error.

**Comment by Jvanrhijn** [comment]
Yeah, I'm seeing the same thing here, not sure what's going on. I'll look into it. As a temporary workaround, you can run the script explicitly using python3 if you have it installed.

**Comment by misterdohl** [comment]
Not sure if im doing it correctly, but running the script with python3 only gives another error :P 
$ python3 spotify_status.py 
<built-in method encode of str object at 0x7f9795f2da08>

**Comment by Jvanrhijn** [comment]
Wat. That looks like the print statement in yours says `print(blah.encode)` instead of `print(blah.encode('utf-8'))`.

Could you paste the entire script you have on your end? Then I'll diff it against mine.

**Comment by misterdohl** [comment]
~~~
$ cat spotify_status.py 
#!/bin/python

import sys
import dbus
import argparse


parser = argparse.ArgumentParser()
parser.add_argument(
    '-t',
    '--trunclen',
    type=int,
    metavar='trunclen'
)
parser.add_argument(
    '-f',
    '--format',
    type=str,
    metavar='custom format',
    dest='custom_format'
)
parser.add_argument(
    '-p',
    '--playpause',
    type=str,
    metavar='play-pause indicator',
    dest='play_pause'
)

args = parser.parse_args()

 Default parameters
output = u'{play_pause} {artist}: {song}'
trunclen = 25
play_pause = u'\u25B6,\u23F8'  first character is play, second is paused

# parameters can be overwritten by args
if args.trunclen is not None:
    trunclen = args.trunclen
if args.custom_format is not None:
    output = args.custom_format
if args.play_pause is not None:
    play_pause = args.play_pause

try:
    session_bus = dbus.SessionBus()
    spotify_bus = session_bus.get_object(
        'org.mpris.MediaPlayer2.spotify',
        '/org/mpris/MediaPlayer2'
    )

    spotify_properties = dbus.Interface(
        spotify_bus,
        'org.freedesktop.DBus.Properties'
    )

    metadata = spotify_properties.Get('org.mpris.MediaPlayer2.Player', 'Metadata')
    status = spotify_properties.Get('org.mpris.MediaPlayer2.Player', 'PlaybackStatus')

    play_pause = play_pause.split(',')
    if status == 'Playing':
        play_pause = play_pause[0]
    elif status == 'Paused':
        play_pause = play_pause[1]
    else:
        play_pause = str()

    artist = metadata['xesam:artist'][0]
    song = metadata['xesam:title']

    if len(song) > trunclen:
        song = song[0:trunclen]
        song += '...' 
        if ('(' in song) and (')' not in song):
            song += ')'

     Python3 uses UTF-8 by default. 
    if sys.version_info.major == 3:
        print(output.format(artist=artist, song=song, play_pause=play_pause).encode )
    else:
        print(output.format(artist=artist, song=song, play_pause=play_pause).encode('utf-8'))
except Exception as e:
    if isinstance(e, dbus.exceptions.DBusException):
        print('')
    else:
        print(e)

~~~

**Comment by Jvanrhijn** [comment]
If you place `~~~` at the start and end of the code block, github ignores the markdown formatting rules like `#` etc :)

In any case, I see what caused your latest issue; somehow, the argument to the encode call in the python 3 print statement has been removed, so it just prints the method. You can just remove the entire function call, python 3 uses utf-8 by default:

~~~python
if sys.version_info.major == 3:
    print(output.format(artist=artist, song=song, play_pause=play_pause ))
~~~

I've got it working for python 2 again on my end, but the current fix gives issues for python 3. I'll push a new version when that works again.

**Comment by misterdohl** [comment]
I'll just wait for a new version, no problem :)

**Comment by Jvanrhijn** [comment]
New version is up, could you test if it's working for you now?

**Comment by misterdohl** [comment]
~~~
$ python spotify_status.py 
⏸ D.D.E.: Det Går Likar No
~~~
works like a charm! thanks :)
